modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/TZBlockBuster/CauldronRevamped/issues"
license = "MIT"

[[mods]]
modId = "cauldronrevamped"
version = "${version}"
displayName = "CauldronRevamped"
authors = "TZBlockBuster"
description = '''
CauldronRevamped reworks the vanilla cauldron, while keeping it as vanilla as possible. It adds the ability to mix potions inside the cauldron.
'''
logoFile = "src/main/resources/assets/cauldronrevamped/icon.png"

[[dependencies.cauldronrevamped]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cauldronrevamped]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cauldronrevamped]]
modId = "architectury"
type = "required"
versionRange = "[19.0.1,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "cauldronrevamped.mixins.json"
